### ISSUE TITLE
Request: when watching an element, show the editor which made the changeset

### ISSUE THREAD

**Issue by pietervdvn** [gander/osm-helper#1]
When inspecting an element, I often find myself clicking the element to see with what piece of software a change was made, as it often gives valuable context. A questionable edit with Maps.me is quite often wrong, while a questionable edit made with OsmAnd is often better because of the higher barrier to make changes with the latter one.

A quick-and-dirty idea of how this might look (the selected text was added by me, but ofc, it shouldn't by highlighted by the user script)

![image](https://github.com/user-attachments/assets/4970532c-c1b8-48d2-b795-5ab314a7afc8)

**Comment by gander** [comment]
ok, I'll try to add it

**Comment by gander** [comment]
@pietervdvn **_PoC_**, it's ok?

![obraz](https://github.com/user-attachments/assets/753cf904-fa65-41a6-85f9-65550a69c7af)

**Comment by pietervdvn** [comment]
Thanks for making this! Look great! It does the job IMHO

Can't wait to test it ;)

**Comment by gander** [comment]
Here is the release: [v0.4.0](https://github.com/gander/osm-helper/releases/tag/v0.4.0)
